name: Build & Test

on: [pull_request]

permissions:
  checks: write

jobs:
  build-java:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11, 17, 21 ]
        distribution: [ temurin ] # We could add more here: temurin, adopt, liberica, microsoft, corretto
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }} ${{ matrix.distribution }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: ${{ matrix.distribution }}
          cache: maven
      - name: Build with Maven # We install instead of package, because we want the result in the local mvn repo
        run: mvn --update-snapshots package
      - name: Stash the built artifacts
        uses: actions/upload-artifact@v4
        if: ${{ matrix.java == 11}}
        with:
          name: smack-tests
          path: target/smack-sint-server-extensions-*-jar-with-dependencies.jar
          retention-days: 1
  test-java:
    name: Test
    runs-on: ubuntu-latest
    needs: build-java
    steps:
      - name: Download the built artifacts
        uses: actions/download-artifact@v4
        with:
          name: smack-tests
          path: .
      - name: Start a test server (Openfire daily)
        uses: igniterealtime/launch-openfire-action@main
        with:
          daily: 'true'
      - name: Run the tests
        run: |
          # Get the jar file by globbing on the version
          JAR_MATCHES=(smack-sint-server-extensions-*-jar-with-dependencies.jar)
          JARFILE=${JAR_MATCHES[0]}

          # Run the tests the same way the action does
          # Borrowing from:
          #  - https://github.com/XMPP-Interop-Testing/xmpp-interop-tests-action/blob/main/action.yml
          #  - https://github.com/igniterealtime/Openfire/blob/ddf144c4ff3b0f753c4087c1e197dfc2bab324a9/.github/workflows/continuous-integration-workflow.yml#L199-L205
          java \
          -Dsinttest.service="example.org" \
          -Dsinttest.host="127.0.0.1" \
          -Dsinttest.securityMode=disabled \
          -Dsinttest.replyTimeout=5000 \
          -Dsinttest.adminAccountUsername=admin \
          -Dsinttest.adminAccountPassword=admin \
          -Dsinttest.enabledConnections=tcp \
          -Dsinttest.dnsResolver=javax \
          -Dsinttest.enabledTests="VCardTempIntegrationTest" \
          -Dsinttest.testRunResultProcessors=org.igniterealtime.smack.inttest.util.StdOutTestRunResultProcessor,org.igniterealtime.smack.inttest.util.JUnitXmlTestRunResultProcessor \
          -Dsinttest.debugger=org.igniterealtime.smack.inttest.util.ModifiedStandardSinttestDebuggerMetaFactory \
          -DlogDir=./target/logs \
          -jar $JARFILE
        shell: bash
      - name: Expose XMPP debug logs
        uses: actions/upload-artifact@v4
        if: always() # always run even if the previous step fails
        with:
          name: XMPP debug logs
          path: logs/*
      - name: Expose Openfire logs
        uses: actions/upload-artifact@v4
        if: always() # always run even if the previous step fails
        with:
          name: Openfire server logs
          path: openfire/logs/*
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/test-results.xml'
          suite_regex: '*'
          include_passed: true
          detailed_summary: true

  build-and-test-docker:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          load: true
          tags: xmpp_interop_tests:testing
      - name: Start a test server (Openfire daily)
        uses: igniterealtime/launch-openfire-action@main
        with:
          daily: 'true'
      - name: Run the tests
        run: |
          docker run \
            --network=host \
            -v "$(pwd)"/xmpplogs:/logs \
            xmpp_interop_tests:testing \
            --domain=example.org \
            --host=127.0.0.1 \
            --timeout=5000 \
            --adminAccountUsername=admin \
            --adminAccountPassword=admin \
            --enabledTests="VCardTempIntegrationTest"
        shell: bash

      - name: Expose XMPP debug logs
        uses: actions/upload-artifact@v4
        if: always() # always run even if the previous step fails
        with:
          name: XMPP debug logs from Docker
          path: xmpplogs/*
      - name: Expose Openfire logs
        uses: actions/upload-artifact@v4
        if: always() # always run even if the previous step fails
        with:
          name: Openfire server logs from Docker test
          path: openfire/logs/*

  build-podman:
    name: Build with Podman
    runs-on: ubuntu-24.04 # Needed for Podman 4.9.3
    steps:
      - uses: actions/checkout@v4
      - name: Build with Podman
        run: podman build -t sintse .
