name: Trigger Downstream Releases

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'The version to trigger, e.g. v1.2.3'
        required: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - id: version
        name: Calculate version to trigger
        run: |
            if [ ${{ github.event_name }} == 'workflow_dispatch' ]; then
                echo "Version: ${{ github.event.inputs.version }}"
                echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
            else
                echo "Version: ${{ github.event.release.tag_name }}"
                echo "version=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
            fi

  github-actions:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Call downstream job for GitHub Actions
        run: |
            curl -L \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.TOKEN_FOR_ACTION_REPO }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/XMPP-Interop-Testing/xmpp-interop-tests-action/dispatches \
                -d '{"event_type":"trigger-workflow","client_payload":{"version":"${{ needs.prepare.outputs.version }}"}}'
  
  circle-ci-orb:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Call downstream job for Circle CI Orb
        run: |
            curl -L \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.TOKEN_FOR_ORB_REPO }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/XMPP-Interop-Testing/xmpp-interop-tests-circleci-orb/dispatches \
                -d '{"event_type":"trigger-workflow","client_payload":{"version":"'"${{ needs.prepare.outputs.version }}"'"}}'

  gitlab-component:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Trigger GitLab pipeline
        run: |
          curl --request POST \
               --form "token=${{ secrets.TOKEN_FOR_GITLAB_COMPONENT_REPO }}" \
               --form "ref=main" \
               --form "variables[VERSION]=${{ needs.prepare.outputs.version }}" \
               --form "variables[TRIGGER_SOURCE]=github" \
               --url "https://gitlab.com/api/v4/projects/56599920/trigger/pipeline"

  forgejo-action:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Trigger Codeberg workflow
        run: |
          VERSION='${{ needs.prepare.outputs.version }}'
          
          INPUTS='{
            "version": "'"${VERSION}"'"
          }'
        
          DATA='{
            "ref": "main",
            "inputs": '"${INPUTS}"'
          }'
        
          curl --request POST \
               --url https://codeberg.org/api/v1/repos/XMPP-Interop-Testing/xmpp-interop-tests-forgejo-action/actions/workflows/upstream_release.yml/dispatches \
               --header 'accept: application/json' \
               --header 'content-type: application/json' \
               --header 'authorization: token ${{ secrets.TOKEN_FOR_CODEBERG_FORGEJO_REPO }}' \
               --data "${DATA}"
