name: Test Entrypoint Script

on: [pull_request]

jobs:
  entrypoint-bats:
    name: Test Entrypoint with BATS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Bats
        run: |
          # Skip installing package docs {makes the man-db trigger much faster)
          sudo tee /etc/dpkg/dpkg.cfg.d/01_nodoc > /dev/null << 'EOF'
          path-exclude /usr/share/doc/*
          path-exclude /usr/share/man/*
          path-exclude /usr/share/info/*
          EOF
          
          sudo apt update
          sudo apt install -y bats bats-assert bats-support
      - name: Setup Bats and Bats-libs
        uses: bats-core/bats-action@3.0.1
        id: setup-bats
        with:
          support-install: "true"
          assert-install: "true"
          detik-install: "false"
          file-install: "false"
      - name: Run entrypoint.bats
        run: |
          export BATS_TEST_MODE=true  # Disable java execution in the entrypoint script
          bats ./test/entrypoint.bats